export const FESkills = [
  "HTML",
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Vitest",
  "Tanstack-Query",
  "Recoil",
  "Zustand",
  "Tailwind CSS",
  "Emotion",
  "Sass",
  "Supabase",
  "AWS S3",
  "CloudFront",
  "Route 53",
  "Github Actions",
  "Illustation",
  "PhotoShop",
  "Xd",
  "Figma",
  "Cinema 4D",
  "Redshift",
  "Jira",
  "Slack",
  "Notion",
  "Github",
];

export const shuffledSkills = [...FESkills].sort(() => Math.random() - 0.5);
